/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: [
          '"SF Pro Text"',
          '"SF Pro Display"',
          '"SF Pro"',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Be Vietnam Pro"',
          'Inter',
          'sans-serif',
        ],
        display: [
          '"SF Pro Display"',
          '"SF Pro Text"',
          '"SF Pro"',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Be Vietnam Pro"',
          'Inter',
          'sans-serif',
        ],
      },
      colors: {
        fm: {
          blue: '#0066cc',
          focus: '#0071e3',
          sky: '#2997ff',
          ink: '#1d1d1f',
          parchment: '#f5f5f7',
          pearl: '#fafafc',
          hairline: '#e0e0e0',
          tile1: '#272729',
          tile2: '#2a2a2c',
          tile3: '#252527',
          muted: '#76767b',
          mutedDark: '#a1a1a6',
          emerald: '#34c759',
          amber: '#ff9500',
          rose: '#ff3b30',
        },
        glass: {
          light: 'rgba(255, 255, 255, 0.78)',
          dark: 'rgba(29, 29, 31, 0.78)',
          borderLight: 'rgba(0, 0, 0, 0.08)',
          borderDark: 'rgba(255, 255, 255, 0.12)',
        },
        macos: {
          blue: 'var(--macos-blue)',
          purple: 'var(--macos-purple)',
          pink: 'var(--macos-pink)',
          red: 'var(--macos-red)',
          orange: 'var(--macos-orange)',
          yellow: 'var(--macos-yellow)',
          green: 'var(--macos-green)',
          mint: 'var(--macos-mint)',
          teal: 'var(--macos-teal)',
          cyan: 'var(--macos-cyan)',
          indigo: 'var(--macos-indigo)',
          brown: 'var(--macos-brown)',
          window: 'var(--macos-window-bg)',
          separator: 'var(--macos-separator)',
          label: {
            primary: 'var(--macos-label-primary)',
            secondary: 'var(--macos-label-secondary)',
            tertiary: 'var(--macos-label-tertiary)',
            quaternary: 'var(--macos-label-quaternary)',
          },
          fill: {
            primary: 'var(--macos-fill-primary)',
            secondary: 'var(--macos-fill-secondary)',
            tertiary: 'var(--macos-fill-tertiary)',
            quaternary: 'var(--macos-fill-quaternary)',
            quinary: 'var(--macos-fill-quinary)',
          },
        },
      },
      borderRadius: {
        'pill': '9999px',
        'lg-panel': '18px',
        'md-panel': '12px',
        'sm-panel': '8px',
      },
      spacing: {
        '4.5': '1.125rem',
        '5.5': '1.375rem',
        '9.5': '2.375rem',
      },
      fontSize: {
        'fm-body': ['15px', { lineHeight: '1.47', letterSpacing: '-0.24px' }],
        'fm-display': ['34px', { lineHeight: '1.15', letterSpacing: '-0.3px' }],
        'fm-hero': ['48px', { lineHeight: '1.08', letterSpacing: '-0.3px' }],
        'macos-large-title': ['26px', { lineHeight: '1.23', letterSpacing: '0.008em' }],
        'macos-title-1': ['22px', { lineHeight: '1.27', letterSpacing: '-0.01em' }],
        'macos-title-2': ['17px', { lineHeight: '1.29', letterSpacing: '-0.012em' }],
        'macos-title-3': ['15px', { lineHeight: '1.33', letterSpacing: '-0.01em' }],
        'macos-headline': ['13px', { lineHeight: '1.38', letterSpacing: '-0.008em' }],
        'macos-body': ['13px', { lineHeight: '1.46', letterSpacing: '-0.005em' }],
        'macos-callout': ['12px', { lineHeight: '1.42', letterSpacing: '0' }],
        'macos-subheadline': ['11px', { lineHeight: '1.36', letterSpacing: '0.006em' }],
        'macos-footnote': ['10px', { lineHeight: '1.4', letterSpacing: '0.012em' }],
        'macos-caption-1': ['10px', { lineHeight: '1.3', letterSpacing: '0.012em' }],
        'macos-caption-2': ['10px', { lineHeight: '1.3', letterSpacing: '0.012em' }],
      },
      boxShadow: {
        'fm-card': '0 8px 24px rgba(0, 0, 0, 0.08)',
        'glass': '0 4px 20px rgba(0, 0, 0, 0.04)',
        'glass-hover': '0 12px 28px -6px rgba(0, 0, 0, 0.08)',
        'glass-dark': '0 8px 32px rgba(0, 0, 0, 0.45)',
        'glass-dark-hover': '0 16px 36px -6px rgba(0, 0, 0, 0.65)',
        'ios-liquid': '0 4px 20px rgba(0, 0, 0, 0.04)',
        'ios-liquid-hover': '0 12px 28px -6px rgba(0, 0, 0, 0.08)',
      },
      transitionDuration: {
        '120': '120ms',
        '160': '160ms',
        '260': '260ms',
        '280': '280ms',
        '320': '320ms',
        '380': '380ms',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'fluid': 'cubic-bezier(0.32, 0.72, 0, 1)',
        'snappy': 'cubic-bezier(0.2, 0.9, 0.2, 1)',
        'exit': 'cubic-bezier(0.3, 0, 0.8, 0.15)',
        'bounce': 'cubic-bezier(0.34, 1.25, 0.64, 1)',
        'ios-fluid': 'cubic-bezier(0.32, 0.72, 0, 1)',
        'ios-bounce': 'cubic-bezier(0.34, 1.25, 0.64, 1)',
        'ios-smooth': 'cubic-bezier(0.25, 1, 0.5, 1)',
      },
      animation: {
        'liquid-float': 'liquidFloat 10s ease-in-out infinite',
        'shimmer': 'shimmer 2.5s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'ios-enter': 'iosEnter 0.35s cubic-bezier(0.16, 1, 0.3, 1) both',
        'ios-caustic': 'iosCaustic 3s cubic-bezier(0.16, 1, 0.3, 1) infinite',
      },
      keyframes: {
        liquidFloat: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-4px)' },
        },
        shimmer: {
          '0%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
          '100%': { opacity: '0.4' },
        },
        iosEnter: {
          '0%': { opacity: '0', transform: 'translateY(8px) scale(0.99)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        iosCaustic: {
          '0%': { transform: 'translateX(-160%) skewX(-22deg)' },
          '100%': { transform: 'translateX(260%) skewX(-22deg)' },
        },
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms')
  ],
}